// routes/adminRoutes.js
import express from 'express';
import {
  getAdminStats,
  getPopularSearches,
  getVisitorStats,
  getAdStats,
  getPerformanceStats,
  exportStats,
  clearStats,
  adminLogin,
  changePassword,
  getAdminProfile,
  updateAdminProfile,
  logout
} from '../controllers/adminController.js';
import {
  getAutoGeneratedBlogs,
  approveAutoBlog,
  deleteAutoBlog,
  getAutoBlogStats
} from '../controllers/adminBlogController.js';
import { authenticateAdmin, loginRateLimit } from '../middleware/authMiddleware.js';

const router = express.Router();

// Public routes
router.post('/login', loginRateLimit, adminLogin);
router.post('/logout', logout);

// Protected routes (require authentication)
router.use(authenticateAdmin);

// Profile management
router.get('/profile', getAdminProfile);
router.put('/profile', updateAdminProfile);
router.put('/change-password', changePassword);

// Statistics
router.get('/stats', getAdminStats);
router.get('/stats/popular-searches', getPopularSearches);
router.get('/stats/visitors', getVisitorStats);
router.get('/stats/ads', getAdStats);
router.get('/stats/performance', getPerformanceStats);
router.get('/stats/export', exportStats);

// Dangerous operations (only for superadmin)
router.delete('/stats/clear', clearStats);

//blog
router.get('/auto-blogs', getAutoGeneratedBlogs);
router.get('/auto-blogs/stats', getAutoBlogStats);
router.put('/auto-blogs/:blogId/approve', approveAutoBlog);
router.delete('/auto-blogs/:blogId', deleteAutoBlog);

export default router;