// routes/blogAutoRoutes.js
import express from 'express';
import Blog from '../models/Blog.js';
import { trackRequest } from '../middleware/ipTracker.js';

const router = express.Router();

// Automatic blog saving endpoint
router.post('/save/auto', trackRequest, async (req, res) => {
  try {
    const {
      title,
      content,
      aiResponse,
      bookDetails,
      userId,
      username = 'Anonymous User',
      tags = [],
      category = 'AI Generated Summaries',
      language = 'en',
      isPublished = true,
      featured = false
    } = req.body;

    // Validate required fields
    if (!title || !content || !aiResponse) {
      return res.status(400).json({
        success: false,
        message: 'Title, content, and AI response are required'
      });
    }

    // Check if similar blog already exists (avoid duplicates)
    const existingBlog = await Blog.findOne({
      $or: [
        { title: { $regex: new RegExp(title.slice(0, 50), 'i') } },
        { 'aiResponse': { $regex: new RegExp(aiResponse.slice(0, 100), 'i') } }
      ],
      createdAt: { $gte: new Date(Date.now() - 24 * 60 * 60 * 1000) } // Last 24 hours
    });

    if (existingBlog) {
      return res.json({
        success: true,
        message: 'Similar blog already exists (duplicate prevented)',
        blog: existingBlog,
        isDuplicate: true
      });
    }

    // Create new blog post
    const blog = new Blog({
      title: title.length > 200 ? title.substring(0, 200) + '...' : title,
      content,
      aiResponse,
      bookDetails: bookDetails || null,
      user: {
        userId: userId || `auto_${Date.now()}`,
        username: username || `User_${(userId || '').slice(-6)}`
      },
      tags: Array.isArray(tags) ? tags.slice(0, 10) : [], // Limit to 10 tags
      category,
      language,
      views: 0,
      likes: [],
      comments: [],
      isPublished,
      featured,
      // Add analytics data
      analytics: {
        ipAddress: req.clientIP || 'unknown',
        userAgent: req.headers['user-agent'] || 'unknown',
        referrer: req.headers['referer'] || 'direct',
        autoGenerated: true,
        generationType: 'ai_summary'
      }
    });

    // Save to database
    await blog.save();

    res.json({
      success: true,
      message: 'Blog post created automatically',
      blog: {
        id: blog._id,
        title: blog.title,
        slug: blog.slug,
        createdAt: blog.createdAt
      }
    });
  } catch (error) {
    console.error('Error in auto blog saving:', error);
    res.status(500).json({
      success: false,
      message: 'Error creating blog post',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined
    });
  }
});

// Get auto-generated blogs
router.get('/auto-generated', async (req, res) => {
  try {
    const { page = 1, limit = 20 } = req.query;
    const skip = (parseInt(page) - 1) * parseInt(limit);

    const query = { 
      'analytics.autoGenerated': true,
      isPublished: true 
    };

    // Get total count
    const total = await Blog.countDocuments(query);

    // Get blogs
    const blogs = await Blog.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(parseInt(limit))
      .select('title slug bookDetails user tags category views likes createdAt')
      .lean();

    res.json({
      success: true,
      blogs: blogs.map(blog => ({
        id: blog._id,
        title: blog.title,
        slug: blog.slug,
        bookTitle: blog.bookDetails?.title,
        bookAuthor: blog.bookDetails?.author,
        userName: blog.user.username,
        tags: blog.tags,
        category: blog.category,
        views: blog.views,
        likesCount: blog.likes.length,
        createdAt: blog.createdAt
      })),
      pagination: {
        currentPage: parseInt(page),
        totalPages: Math.ceil(total / parseInt(limit)),
        totalItems: total
      }
    });
  } catch (error) {
    console.error('Error fetching auto-generated blogs:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching blogs'
    });
  }
});

export default router;