import Blog from '../models/Blog.js';
import mongoose from 'mongoose';

class BlogCleanupService {
  constructor() {
    this.checkInterval = 24 * 60 * 60 * 1000; // 24 hours
  }

  start() {
    console.log('Starting blog cleanup service...');
    setInterval(() => this.cleanupOldBlogs(), this.checkInterval);
    // Run once on startup
    setTimeout(() => this.cleanupOldBlogs(), 10000);
  }

  async cleanupOldBlogs() {
    try {
      console.log('Running blog cleanup...');
      
      // Delete auto-generated blogs older than 90 days with low engagement
      const ninetyDaysAgo = new Date(Date.now() - 90 * 24 * 60 * 60 * 1000);
      
      const result = await Blog.deleteMany({
        isAutoGenerated: true,
        createdAt: { $lt: ninetyDaysAgo },
        views: { $lt: 10 }, // Less than 10 views
        likes: { $size: 0 } // No likes
      });
      
      console.log(`Cleaned up ${result.deletedCount} old auto-blogs`);
      
      // Clean up duplicates (keep only the first one)
      await this.removeDuplicates();
      
    } catch (error) {
      console.error('Error in blog cleanup:', error);
    }
  }

  async removeDuplicates() {
    try {
      // Find blogs with similar titles/content
      const duplicateGroups = await Blog.aggregate([
        {
          $match: { isAutoGenerated: true }
        },
        {
          $group: {
            _id: {
              title: { $substr: ['$title', 0, 50] }
            },
            count: { $sum: 1 },
            blogs: { $push: '$$ROOT' }
          }
        },
        {
          $match: { count: { $gt: 1 } }
        }
      ]);
      
      let deletedCount = 0;
      
      for (const group of duplicateGroups) {
        // Sort by creation date (keep the oldest)
        const sortedBlogs = group.blogs.sort((a, b) => 
          new Date(a.createdAt) - new Date(b.createdAt)
        );
        
        // Delete all except the first one
        const blogsToDelete = sortedBlogs.slice(1);
        
        for (const blog of blogsToDelete) {
          await Blog.deleteOne({ _id: blog._id });
          deletedCount++;
        }
      }
      
      if (deletedCount > 0) {
        console.log(`Removed ${deletedCount} duplicate blogs`);
      }
      
    } catch (error) {
      console.error('Error removing duplicates:', error);
    }
  }
}

// Create and export singleton
const blogCleanupService = new BlogCleanupService();
export default blogCleanupService;